export const FETCH_POKEMON_START = "FETCH_POKEMON_START";
export const FETCH_POKEMON_SUCCESS = "FETCH_POKEMON_SUCCESS";
export const FETCH_POKEMON_FAIL = "FETCH_POKEMON_FAIL";
export const VIEW_POKEMON_DATA = "VIEW_POKEMON_DATA";
export const ADD_POKEMON_TO_LINEUP = "ADD_POKEMON_TO_LINEUP";
export const REMOVE_POKEMON_FROM_LINEUP = "REMOVE_POKEMON_FROM_LINEUP";