export const LOAD_PROFILE_START = "LOAD_PROFILE_START";
export const LOAD_PROFILE_SUCCESS = "LOAD_PROFILE_SUCCESS";
export const LOAD_PROFILE_FAIL = "LOAD_PROFILE_FAIL";

export const ADD_POKEMON_TO_LINEUP_START = "ADD_POKEMON_TO_LINEUP_START";
export const ADD_POKEMON_TO_LINEUP_SUCCESS = "ADD_POKEMON_TO_LINEUP_SUCCESS";
export const ADD_POKEMON_TO_LINEUP_FAIL = "ADD_POKEMON_TO_LINEUP_FAIL";

export const REMOVE_POKEMON_FROM_LINEUP_START = "REMOVE_POKEMON_FROM_LINEUP_START";
export const REMOVE_POKEMON_FROM_LINEUP_SUCCESS = "REMOVE_POKEMON_FROM_LINEUP_SUCCESS";
export const REMOVE_POKEMON_FROM_LINEUP_FAIL = "REMOVE_POKEMON_FROM_LINEUP_FAIL";

export const UPDATE_PROFILE_START = "UPDATE_PROFILE_START";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_START_FAIL";