export const FETCH_POKEMON_START = "FETCH_POKEMON_START";
export const FETCH_POKEMON_SUCCESS = "FETCH_POKEMON_SUCCESS";
export const FETCH_POKEMON_FAIL = "FETCH_POKEMON_FAIL";
export const SELECT_POKEMON = "SELECT_POKEMON";
export const DESELECT_POKEMON = "DESELECT_POKEMON";
export const UPDATE_POKEMON_QUERY = "UPDATE_POKEMON_QUERY";